export const jokes = [
  "Why do programmers prefer dark mode? Because the light attracts bugs!",
  "Why did the web developer go broke? Because he used up all his cache.",
  "How do you comfort a JavaScript bug? You console it.",
  "Why don't web developers ever play hide and seek? Because good luck hiding when you can't find the closing tag.",
  "Why was the JavaScript developer so good at parties? Because he knew how to 'callback'!",
  "What's a web developer's favorite type of music? Anything with good 'breakpoints'!",
  "Why did the HTML file break up with the CSS? Because it was tired of being styled.",
  "How many web developers does it take to change a light bulb? None. It's a hardware problem!",
  "Why did the web developer hate nature? It had too many bugs.",
  "Why did the CSS file go to therapy? It had issues with its layout.",
  "What do you call a website that always complains? A blog!",
  "How do you know a web developer is at your party? Don't worry, they'll tell you.",
  "Why was the database so calm? Because it had good indexes.",
  "What's a web developer's favorite drink? Java!",
  "Why do Java developers wear glasses? Because they can't C#.",
  "What did the JavaScript say to the HTML? You're so 'elementary'!",
  "Why do web developers like to keep their code tidy? So they don't get caught in a loop!",
  "Why do web developers make terrible comedians? They don't know when to 'end' the joke.",
  "What did the HTML say to the CSS? You complete me!",
  "Why do web developers hate shopping? They're always worried about 'responsive' design.",
];
